sudo: false
env:
  global:
    # ALINODE_SECRET=xx
    - secure: "dlBiU40QbwxRA5mhKBcIwyY0AxbAMnQ5dOSjywuWeKzOPQruvnwyUgx3wd9LHio3o9gvJbhfu9QTzyDJNkDfTMgEnAzMYyxBgoPqt8nW7+xg9PsxDHVhK3cX8m8rp5bCgOB1m+gishcNfwIO1tXkLdrlS7PKnKWrH50dvKGLUlfvf6Hb5rvJuHIJMxbAtuQ7OfPvUbCvi/ClFb4JwIEvdykgkcZbtAw7wicR8Q16u9p5QzN+6IGMAaICeGnqlQ7U/FazF6uohJ0Qzt905GJXOXOz4z7fL2kNeKmrWy2GjR99Kr4HGeP90NXeK4uupbYrI6RQCSFzVBKKC1c38f9yd6kBunKXB3BXHA0PDpO+eou8/yY106uPPp5fb06oRStRxKNgbnaF8waIkqUvEvFjivO+dg0rqE+6wDUcCVOVou0TOIuIuT5zgsL+KHqZwtR1vmda2d4klUIJOyVNdFFtBbB5Qwf7rDv0alDjY64es7TW1W8nhx4wB5verTiX73JKX6GL0snVE87HLmKbb/cxOi4YtOyMSWw1KFcPljuBREYNx6L6k6WgMI5r5fPGUoEQ6n3OllkN1tD3KXBhh92XiYsNYWcHfvMsafRUauZ5hr7XLZEICOUTRvY0wAh/mT4YL2jo1L5W25BBi1Wu+EtBqmbtrIkjNOELLSeRnEYo/Uo="
    # ALINODE_APPID=xx
    - secure: "oq/r256YerasM8VXoPbXldYRG3JfflHuDVknaRCaW2IedRc+3HQjFE7CvnTUgm7XDaOrDYgKasBIwKo8ohu520v1tSJab/3vNuGZERCC1AczXLSMAeacEPrhEuqmHv03JoySLgqFbqI35MFZyMTuIp46uQ18tOmhUoAynZjoZPD1Boc/Sp5cLY+WbFVOQiYs6xBvtad1CwxZah/fOCK2393N7H/9d4oS8lDLh+cqqgdmm/yhrE4SZUpQXrmJDySQ92aysThjfYcAJz0a6E4QgKYfbLk7y5E3yMa0zAzwH/P3sjRXVDnT9yZ0w3b5oShRnV3yRoNQ+gwtwSGdk2wFut5Se3RsDjoldhtYzL6o2MXRCt6pyWQwMtjBDRJs4ZVSSsWOuyTksUd3HyaOvj0SHI253KmC1q0GH8aDeVBZZv1VpmCLQNFIllxnQ5s2Dt4OStdkHfV8z7sg+xQl7jfj5jxmwD9D5RKvbPNPOkstmtb4+xcMMRvMkVCB4LBYO8HX2IXmIXsiJTn1s0p+0u8Fu/UnwLurI4GaWIXeuzlIf9MCfrEMykYRWl477v7rksBnY3z5qucqFomZepvtclk1ihoAXcbhv6e7HOgpFL7tK6l+3U1S0kW1eIlQcWIM2NFIexJU7o1A5PtGf+Dw8XUQSkDbJoWlZ7Ey3wmVtApMyQ4="
language: node_js
node_js:
  - '4'
  - '6'
install:
  - npm i npminstall && npminstall
script:
  - npm run ci
after_script:
  - npm i codecov && codecov
